# Server
server.port=9091

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/jayeondeule
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Wkdusemfdp1@}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# File Upload
spring.servlet.multipart.max-file-size=700MB
spring.servlet.multipart.max-request-size=1100MB
board.upload.path=/workspace/jayeondeule/shop/uploads/board

# JWT
jwt.secret=${JWT_SECRET:jayeondeuleShopService:Wkdusmfdp1@}
jwt.expiration=604800000
