# ?????? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/jayeondeule
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Wkdusemfdp1@}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DEBUG 시 SQL 쿼리 및 파라미터 로깅
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.config.import=classpath:/application/application-springdoc.yml

server.port=9090

jwt.secret=${JWT_SECRET:jayeondeuleWebService:Wkdusmfdp1@}